apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    component: kibana
spec:
  selector:
    app: kibana
  type: LoadBalancer
  ports:
  - port: 80
    name: webinterface
    targetPort: 5601


#  ports:
#  - name: http
#    port: 5601
#    protocol: TCP
